export const REQUEST_FETCH_USERS = 'REQUEST_FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_ADMINS = 'FETCH_ADMINS';
